### ISSUE TITLE
reference is red, the message under it says there's no version for .NETportable

### ISSUE THREAD

**Issue by 7sharp9** [alexy/EffinPickle#1]
That is bug in **Xamarin Studio**.  It is fixed in the Embedded F# branch which will be released in the near future, although the reference is red the solution can still be installed.

If you remove the FSharp.Core reference from a project then one will eb implicitly added for the current version of the target framework e.g .Net 4.0/4.5/4.5.1 but not currently portable targets.   

Currently FSharp.Core is built loosely around profile47 and the portable project template has a explicit reference to that version, this is required.  Only profile 7 is available in Windows.

It should be possible to build other versions of FSharp.Core to suite the needs of various profiles it just a matter of getting some time to do this.  The work done on the F# addin and open source F# compiler is all done in people free time.

**Comment by alexy** [comment]
OK -- so if I just create an empty F# PCL, called Fpcl.Core, it's created with Profile 136 and I get 1 warning and 2 errors:

/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/4.5/Microsoft.Common.targets: Warning: Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.0,Profile=Profile47'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior. (Fpcl.Core)

/Users/Alexy/Projects/Fpcl/Fpcl.Core: Error FS0219: The referenced or default base CLI library 'mscorlib' is binary-incompatible with the referenced F# core library '/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/gac/FSharp.Core/2.3.5.1__b03f5f7f11d50a3a/FSharp.Core.dll'. Consider recompiling the library or making an explicit reference to a version of this library that matches the CLI version you are using. (FS0219) (Fpcl.Core)

/Users/Alexy/Projects/Fpcl/Fpcl.Core: Error FS0218: Unable to read assembly '/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/gac/FSharp.Core/2.3.5.1__b03f5f7f11d50a3a/FSharp.Core.dll' (FS0218) (Fpcl.Core)

These don't change if I switch to Profile 47.  I clearly have some old FSharp.Core in the GAC...  My Mono came from Xamarin Studio Alpha and then fsharp install form code last night.  Is this expected?

**Comment by 7sharp9** [comment]
The latest version of F# should install FSharp.Core/2.3.5.1 to the GAC.  Is it present in the lib/release folder where you built the F#?

**Comment by alexy** [comment]
```
ls -l /Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/gac/FSharp.Core/2.3.5.1__b03f5f7f11d50a3a/FSharp.Core.dll
-rwxr-xr-x  1 root  admin  1206784 Feb 23 02:53 /Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/gac/FSharp.Core/2.3.5.1__b03f5f7f11d50a3a/FSharp.Core.dll
```

It'c clearly there, and I can edit references and add it explicitly, still getting both errors as above.  If I add that 2.3.5.1 version explicitly and remove the red one, I get 2 errors and 2 warnings:

```
/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/4.5/Microsoft.Common.targets: Warning: Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.0,Profile=Profile47'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior. (Fpcl.Core)

/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/4.5/Microsoft.Common.targets: Warning: Reference 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' not resolved (Fpcl.Core)

/Users/Alexy/Projects/Fpcl/Fpcl.Core: Error FS0219: The referenced or default base CLI library 'mscorlib' is binary-incompatible with the referenced F# core library '/Users/Alexy/Projects/Fpcl/Fpcl.Core/../../../../../Library/Frameworks/Mono.framework/Versions/Current/lib/mono/portable-net45+sl5+win8/FSharp.Core.dll'. Consider recompiling the library or making an explicit reference to a version of this library that matches the CLI version you are using. (FS0219) (Fpcl.Core)

/Users/Alexy/Projects/Fpcl/Fpcl.Core: Error FS0218: Unable to read assembly '/Users/Alexy/Projects/Fpcl/Fpcl.Core/../../../../../Library/Frameworks/Mono.framework/Versions/Current/lib/mono/portable-net45+sl5+win8/FSharp.Core.dll' (FS0218) (Fpcl.Core)
```

**Comment by 7sharp9** [comment]
Are all the PCL re-distributables installed in `/Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/xbuild-frameworks/.NETPortable/*`?

**Comment by alexy** [comment]
```
$ ls /Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/xbuild-frameworks/.NETPortable/v4.5
Microsoft.CSharp.dll                              System.IO.dll                                         System.Resources.ResourceManager.dll              System.Text.Encoding.Extensions.dll
Microsoft.VisualBasic.dll                         System.Linq.Expressions.dll                           System.Runtime.Extensions.dll                     System.Text.Encoding.dll
```

... -- a gazillion more for v4.5, but only a few in v4.0, here's the full list:

```
$ ls /Library/Frameworks/Mono.framework/Versions/3.2.7/lib/mono/xbuild-frameworks/.NETPortable/v4.0
Microsoft.CSharp.dll                      System.ComponentModel.DataAnnotations.dll System.Runtime.Serialization.dll          System.Xml.Linq.dll                       mscorlib.dll
Profile                                   System.Core.dll                           System.ServiceModel.Web.dll               System.Xml.Serialization.dll
RedistList                                System.Net.dll                            System.ServiceModel.dll                   System.Xml.dll
System.ComponentModel.Composition.dll     System.Numerics.dll                       System.Windows.dll                        System.dll
```

**Comment by 7sharp9** [comment]
OK, so its the original error then `INotifyPropertyChanged` is missing, Ill see where that is defined.

**Comment by alexy** [comment]
So the above errors are for just the empty F# PCL project before I even get to add any files to it.  The `INotifyPropertyChanged` happens when we add all the MvvmCross packages via NuGet and App.fs/FirstViewModel.fs files.

If we just create an F# Portable Library project from template and immediately build it, should we get "build successfull"?

**Comment by 7sharp9** [comment]
The empty project should build fine, if it doesn't then raise an issue [here](https://github.com/fsharp/fsharpbinding/issues?direction=desc&labels=&page=1&sort=created&state=open)

**Comment by alexy** [comment]
Added: https://github.com/fsharp/fsharpbinding/issues/338

**Comment by paulyoung** [comment]
@alexy, @7sharp9 can either of you speak to the current state of developing F# PCLs for use in cross-platform apps with Xamarin Studio on OS X?

This and most other threads are quite old but I'm running into the same issues.

**Comment by 7sharp9** [comment]
@paulyoung There is no official support for an F# pcl template currently although It is possible to manually create one by changing the project file.   

You may encounter red squiggles in the IDE but the project will compile.  This will be fixed in the next version of Xamarin Studio, and possibly pcl templates for profiles 78/259.

**Comment by paulyoung** [comment]
Thanks @7sharp9!
